Category/urls.py
from django.urls import path
from . import views

app_name = 'Category'

urlpatterns = [
    path('', views.MainList.as_view(), name='sex_toys'),
    path('<slug:slugname>/', views.CategoryList.as_view(), name='sex_toys_slug'),
]

GGKala/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from account.views import Login, signup, activate


urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path('signup/', signup, name="signup"),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('Home.urls')),
    path('account/', include('account.urls')),
    path('category/', include('Category.urls')),
    path('products/', include('Products.urls')),
    path('review/', include('review.urls')),

]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/urls.py
from django.urls import path
from . import views

app_name = "Home"

urlpatterns = [
    path('', views.home_page, name='home'),
    path('publisher/<slug:publisher>/', views.PublisherList.as_view(), name='publisher_url'),
]

Products/urls.py
from django.urls import path
from . import views

app_name = 'Products'

urlpatterns = [
    path('<slug:slugname>/', views.detail, name='detail'),
    path('preview/<int:pk>/', views.DetailPreview.as_view(), name='preview'),
]

Category/models.py
from django.db import models
from account.models import User
from django.template.defaultfilters import truncatechars
from django.utils.html import format_html
from django.utils.formats import date_format
from django.urls import reverse

# from multiselectfield import MultiSelectField | for multiplay chois

# Manager


class CategoryManager(models.Manager):
    def return_truestatus(self):
        return self.filter(status="True")


class Category(models.Model):
    parent = models.ForeignKey('self', default=None, blank=True, null=True, on_delete=models.SET_NULL, related_name='parents_related')
    category_name = models.CharField(max_length=100)
    page_title = models.CharField(max_length=30, default="جی جی کالا")
    slug = models.SlugField(unique=True)
    status = models.BooleanField(default=True)
    caption = models.TextField(default="")
    photo = models.ImageField(upload_to="Sex-Toys-photo", blank=True)
    position = models.IntegerField(unique=True)

    class Meta:
        ordering = ['parent__id', 'position']

    def __str__(self):
        return self.category_name

    objects = CategoryManager()


def show_category(obj):
    return ", ".join([cat.category_name for cat in obj.category.return_truestatus()])

Category/forms.py
from django import forms
from . import models

class Update(forms.ModelForm):
    class Meta:
        model = models.SexToys
        fields = ['title', 'about']

Category/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView
from . import models
from Products.models import SexToys
from django.db.models import Count, Avg


class MainList(ListView):
    template_name = 'Category/sextoys_list.html'
    queryset = SexToys.object.return_published_product()


class CategoryList(ListView):
    paginate_by = 28
    template_name = 'Category/sex_toys_slug.html'

    def get_queryset(self):
        global category
        global sorted_by
        global averege_rate

        sorted_by = self.request.GET.get('sorted-by')
        slug = self.kwargs.get('slugname')
        category = get_object_or_404(models.Category.objects.return_truestatus(), slug=slug)
        f = category.sexy_toys_related_name.return_published_product()

        if sorted_by == "score":
            return f.annotate(res_off=Avg('review__rate')).order_by('-res_off')
        elif sorted_by == "newst":
            return f
        elif sorted_by == "price-down":
            return f.order_by('real')
        elif sorted_by == "price-up":
            return f.order_by('-real')
        else:
            return f.annotate(res_off=Count('hits')).order_by('-res_off')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cat'] = category
        context['val'] = sorted_by
        return context

Category/templates/Category/sex_toys_slug.html
{% extends  'GGkala/base.html' %}
{% load static %}
{% load humanize %}
{% load ratings %}
{% load main_tags %}


{% block title %} {{ cat.page_title }} | جی جی کالا {% endblock %}

{% block css %}
    {% static 'Category/css/sex_toys.css' %}
{% endblock %}
{% block add_css %}
    <link rel="stylesheet" href="{% static 'Category/css/sex-toys-responsive.css' %}">
{% endblock %}


{% block body %}
    <div class="product-page-all">

        <div class="caption-margin">
            <div class="caption-name"> اسباب بازی {{ cat.category_name }}</div>
            <div class="caption">{{ cat.caption }}</div>
        </div>

        <div class="margin-product">
            <div class="product-holder-all">
                <div class="filter-list">

                </div>
                <div class="product-season-holder">

                    <div class="count-and-else">
                        <div class="count-text-pr"> {% fa_number cat.sexy_toys_related_name.count %}  محصول</div>
                        <div style="position:relative;">
                            <form action="" method="get">
                                <label for="2" class="yekan-font">مرتب سازی:</label>
                                <select onchange="this.form.submit()" class="sorted-by-select-tag" name="sorted-by" id="2">
                                    <option {% if val == "popular" %} selected="selected" {% endif %} value="popular">محبوب ترین</option>
                                    <option {% if val == "score" %} selected="selected" {% endif %} value="score">امتیاز بالا</option>
                                    <option {% if val == "newst" %} selected="selected" {% endif %} value="newst">جدید ترین</option>
                                    <option {% if val == "price-down" %} selected="selected" {% endif %} value="price-down">ارزان ترین</option>
                                    <option {% if val == "price-up" %} selected="selected" {% endif %} value="price-up">گران ترین</option>
                                </select>
                                <img class="down-image" src="{% static 'Category/images/down.png' %}" alt="">
                            </form>
                        </div>
                    </div>

                    <div class="item-holder">
                        {% for i in object_list %}
                            <div class="proudoct-holder">
                                <a href="{% url 'Products:detail' i.slug %}" class="a-product">

                                    <div class="proudoct_img">
                                        {% if i.off and i.off != null  %}
                                            <div class="off-show">
                                                <div class="off-text"> {{ i.off }}% تخفیف <img class="img-off-back" src="{% static 'Category/images/back.png' %}" alt=""></div>
                                            </div>
                                        {% endif %}
                                        <img class="product_img_main" src="{{ i.photo.url }}" alt="">
                                    </div>

                                    <div class="product-specifications">

                                        <div class="star-holder">
                                            {% average_rate i.review.all %}
                                            <div class="star-count">({{ i.review.count }})</div>
                                        </div>

                                        <div class="title-div">
                                            <div class="title">{{ i.title }}</div>
                                        </div>

                                        <div class="price-holder">
                                            {% if i.off %}
                                                <div class="off-holder">
                                                    <div class="toman-off-disabled">
                                                        <div class="price-text" style="font-size: 17px;margin-left: 10px; text-decoration: line-through;">
                                                            {{ i.price|intcomma:False }}
                                                        </div>
                                                    </div>
                                                    <div class="toman-off">
                                                        <div class="price-text" style="color: #ff0000;">
                                                            {{ i.discounted_price|intcomma:False }}
                                                        </div>
                                                        <img class="price-photo-toman" src="{% static 'Category/images/toman-red.png' %}" alt="">
                                                    </div>
                                                </div>
                                            {% else %}
                                                <img class="price-photo-toman" src="{% static 'Category/images/toman.png' %}" alt="">
                                                <div class="price-text">
                                                    {{ i.price|intcomma:False }}
                                                </div>
                                            {% endif %}
                                        </div>

                                        <div class="colors">

                                            {% for color in i.color.all %}
                                                {% if forloop.counter <= 3 %}
                                                    <div class="just-for-hover">
                                                        <div class="p-d-l">
                                                            <div class="color" style="background-color: {{ color.color_rgb }};"></div>
                                                        </div>
                                                    </div>
                                                {% elif forloop.counter == 4 %}
                                                    <img src="{% static 'Category/images/add.png' %}" class="color" style="border: none;" alt="">
                                                {% endif %}

                                            {% endfor %}

                                        </div>

                                    </div>
                                </a>

                            </div>
                        {% endfor %}
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

Category/templates/Category/sextoys_list.html
{% extends  'GGkala/base.html' %}

{% block title %} اسباب بازی ها جنسی | خرید آنلاین اسباب بازی های بزرگسالان | جی جی کالا {% endblock %}

{% block body %}

{% endblock %}