Category/urls.py
from django.urls import path
from . import views

app_name = 'Category'

urlpatterns = [
    path('', views.MainList.as_view(), name='sex_toys'),
    path('<slug:slugname>/', views.CategoryList.as_view(), name='sex_toys_slug'),
]

GGKala/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from account.views import Login, signup, activate


urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path('signup/', signup, name="signup"),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('Home.urls')),
    path('account/', include('account.urls')),
    path('category/', include('Category.urls')),
    path('products/', include('Products.urls')),
    path('review/', include('review.urls')),

]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/urls.py
from django.urls import path
from . import views

app_name = "Home"

urlpatterns = [
    path('', views.home_page, name='home'),
    path('publisher/<slug:publisher>/', views.PublisherList.as_view(), name='publisher_url'),
]

templates/GGkala/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa-IR">
<head>

    <meta charset="UTF-8">
    <title> {% block title %} {% endblock %} </title>
    <link rel="stylesheet" href="{% block css %} {% endblock %}">
    {% block add_css %}{% endblock %}
    <link rel="stylesheet" href="{% static 'GGkala/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'GGkala/css/header-responsive.css' %}">
    <link rel="stylesheet" href="{% static 'GGkala/css/message.css' %}">
    <link rel="stylesheet" href="{% static 'review/css/review-style.css' %}">
</head>
<body>

{% include 'GGkala/header.html' %}
{% include 'GGkala/messages.html' %}
{% block body %}{% endblock %}

</body>
</html>

templates/GGkala/category_show.html
{% load static %}

<div class="category-marg">
    <div class="category-holder">
        <div class="category-shoping-text">
            دسته بندی های جی جی کالا
        </div>

        <div class="category-holder-main">
            <div class="cat-holder">

                <a href="{% url 'Category:sex_toys_slug' 'dildo' %}" class="cat">
                    <img class="cet-image" src="{% static 'GGkala/images/dildo.png' %}" alt="">
                    <span class="cat-text" style="top:37%;">دیلدو</span>
                </a>

                <a href="{% url 'Category:sex_toys_slug' 'couples' %}" class="cat">
                    <img class="cet-image" src="{% static 'GGkala/images/couples.png' %}" alt="">
                    <span class="cat-text" style="top:37%;">برای زوج ها</span>
                </a>

                <a href="{% url 'Category:sex_toys_slug' 'for-male' %}" class="cat">
                    <img class="cet-image" src="{% static 'GGkala/images/male.png' %}" alt="">
                    <span class="cat-text">دسته‌بندی <br>مردان</span>
                </a>

                <a href="{% url 'Category:sex_toys_slug' 'vibrator' %}" class="cat">
                    <img class="cet-image" src="{% static 'GGkala/images/vib.png' %}" alt="">
                    <span class="cat-text" style="top:37%;">ویبراتور</span>
                </a>

            </div>

            <div class="cat-holder">
                <a href="{% url 'Category:sex_toys_slug' 'cock-ring' %}" class="cat">
                    <img class="cet-image" src="{% static 'GGkala/images/cock-ring.png' %}" alt="">
                    <span class="cat-text">دسته‌بندی <br>حلقه آلت</span>
                </a>

                <a href="{% url 'Category:sex_toys_slug' 'rabbit' %}" class="cat">
                    <img class="cet-image" src="{% static 'GGkala/images/rabbit.png' %}" alt="">
                    <span class="cat-text" style="top:37%;">خرگوشی</span>
                </a>

                <a href="{% url 'Category:sex_toys_slug' 'anal-toys' %}" class="cat">
                    <img class="cet-image" src="{% static 'GGkala/images/anal-toys.png' %}" alt="">
                    <span class="cat-text">دسته‌بندی <br>آنال</span>
                </a>

                <a href="{% url 'Category:sex_toys_slug' 'clitoral' %}" class="cat">
                    <img class="cet-image" src="{% static 'GGkala/images/clitros.png' %}" alt="">
                    <span class="cat-text">دسته‌بندی <br>کلیتروس</span>
                </a>
            </div>
        </div>
    </div>
</div>

templates/GGkala/header.html
{% load static %}
<div class="navbar_all">
    <div class="search-logo-icon-holder">

        <div class="icons">

            <div class="user-holder">
                <img class="user" src="{% static 'GGkala/images/profile.png' %}" alt="">

                {% if user.is_anonymous %}
                    <a href="{% url 'login' %}" class="text-user"><span> ورود | ثبت نام</span></a>
                {% else %}
                    <a href="{% url 'logout' %}" class="text-user"><span> {{ user.get_full_name|truncatechars:15 }} </span></a>
                {% endif %}

            </div>
            <a href="#" class="icon m-l-10 p-t">
                <img style="height: 23px;margin-top: 1px;" src="{% static 'GGkala/images/heart.png' %}" alt="">
            </a>
            <a href="#" class="icon m-l-10 p-t">
                <img style="height: 23px;" src="{% static 'GGkala/images/shopping-bag.png' %}" alt="">
            </a>

        </div>

        <div style="display: flex;align-items: center;">

            <div class="logo-flex">
                <a href="{% url 'Home:home' %}" style="text-decoration: none;">
                    <div class="gg-kala-logo">
                        <img class="logo_images" src="{% static 'GGkala/images/logo.png' %}" alt="">
                    </div>
                </a>
            </div>

            <div class="searc-holder">
                <div class="search-button">
                    <input alt="Submit" type="image" aria-label="#" class="search-img-input"
                           src="{% static 'GGkala/images/search_white.png' %}">
                </div>
                <input aria-label="hello" placeholder="جستجو کنید ..." class="search">
            </div>
        </div>

    </div>

    <div class="meno-holder">

        <ul>
            <li class="meno-li">
                <a href="{% url "Category:sex_toys" %}" class="meno_style" style="font-weight: bold;">اسباب‌بازی های جنسی</a>
            </li>

            <li class="meno-li">
                <a href="{% url "Category:sex_toys_slug" "vibrator" %}" class="meno_style">ویبراتور</a>
            </li>

            <li class="meno-li">
                <a href="{% url "Category:sex_toys_slug" "dildo" %}" class="meno_style">دیلدو</a>
            </li>

            <li class="meno-li">
                <a href="#" class="meno_style">برای مردها</a>
            </li>

            <li class="meno-li">
                <a href="#" class="meno_style">بانداژ</a>
            </li>

            <li class="meno-li">
                <a href="#" class="meno_style">روان‌کننده و روغن</a>
            </li>

            <li class="meno-li">
                <a href="#" class="meno_style">لباس‌زیر</a>
            </li>

            <li class="meno-li">
                <a href="#" class="meno_style">مشاوره</a>
            </li>

            <li class="meno-li">
                <a href="#" class="meno_style" style="color: #ff0033;">سلامت‌جنسی</a>
            </li>
        </ul>

        <a href="#" class="selecte-location-holder">
            <img src="{% static 'GGkala/images/location.png' %}" class="selecte-location-img" alt="">
            <div class="selecte-location-text">لطفا شهر خود را انتخاب کنید</div>
        </a>

    </div>


</div>

<div class="news">
    <div id="slider">
        <ul>
            <li>
                <div class="slider-container">
                    <p>خرید اول، هیجان انگیز تر از همیشه با 30 درصد تخفیف!</p>
                </div>
            </li>
            <li>
                <div class="slider-container">
                    <p>با خرید اولین ویبراتور، یک مکنده رایگان هدیه بگیرید!</p>
                </div>
            </li>
            <li>
                <div class="slider-container">
                    <p>روز سکس مبارک! تخفیف ویژه برای بانداژ و لوازم زناشویی.</p>
                </div>
            </li>
        </ul>
    </div>


</div>

templates/GGkala/messages.html
{% if messages %}

    {% for message in messages %}
        <label>
            <input type="checkbox" class="alertCheckbox" autocomplete="off" />
            <div class="alert {% if message.tags %} {{ message.tags }} {% endif %}>">
                <span class="alertClose">X</span>
                <span class="alertText">{{ message }}
		<br class="clear"/></span>
            </div>
        </label>
    {% endfor %}

{% endif %}

templates/GGkala/servic.html
{% load static %}

<div class="mar">
    <div class="services-holder">

        <div class="servic_option">
            <div class="servic_mar">
                <div class="packaging-holder">
                    <img class="packaging-img" src="{% static 'Home/images/packaging.png' %}" alt="">
                    <div class="packaging-text"> بسته بندی کاملا <br>محتاطانه</div>
                </div>

                <div class="packaging-holder">
                    <img class="shipping-img" src="{% static 'Home/images/shipping.png' %}" alt="">
                    <div class="packaging-text"> ارسال رایگان برای <br>سفارش بالای دو میلیون تومان</div>
                </div>

                <div class="packaging-holder">
                    <img class="suport-img" src="{% static 'Home/images/suport.png' %}" alt="">
                    <div class="packaging-text"> ۲۴/۷ پشتیبانی با چت و ایمیل</div>
                </div>

                <div class="packaging-holder">
                    <img class="suport-img" src="{% static 'Home/images/garantie.png' %}" alt="">
                    <div class="packaging-text">100 روز ضمانت بازگشت کالا<br> برای اسباب بازی و بانداژ</div>
                </div>
            </div>
        </div>

    </div>
</div>